CREATE DATABASE code
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_unicode_ci;
 
USE code;
 
CREATE TABLE users (
	id INT NOT NULL AUTO_INCREMENT,
	name CHAR(30) NOT NULL,
	email CHAR(50) NOT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB;